### ISSUE TITLE
Unable to get svg animation properly in my website

### ISSUE THREAD

**Issue by arnavj05** [santhoshtr/mlmash#2]
Sir I am currently a summer intern at Homi Bhabha Centre for Science Education(HBCSE) and we are currently working on naYana teaching website. Your project has been very useful and inspirational to us. We are unable to animate the fill portion in the SVG in the visual dictionary section of naYana site in a specific direction. I would like to connect with you and seek your guidance. I am attaching the Gitlab link of our website for your reference. Thanks in advance.

[https://gitlab.com/gnowledge/lernayana](url)

**Comment by santhoshtr** [comment]
Did you solve your issue? I had documented its functioning at https://thottingal.in//blog/2020/10/27/learning-to-write-malayalam-svg-animation/

**Comment by arnavj05** [comment]
Yes,
The issue was resolved.

Thank you
